# This rule is not used by the project users itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to kcp.cogniteo.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: users
    app.kubernetes.io/managed-by: kustomize
  name: user-viewer-role
rules:
- apiGroups:
  - kcp.cogniteo.io
  resources:
  - users
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kcp.cogniteo.io
  resources:
  - users/status
  verbs:
  - get
