apiVersion: kcp.cogniteo.io/v1alpha1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: users
    app.kubernetes.io/managed-by: kustomize
  name: user-sample
spec:
  # TODO(user): Add fields here
