name: Auto Version on Master Merge

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  auto-version:
    name: Create version tag on master merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version bump
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: false

      - name: Create and push tag
        if: steps.version.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "Creating tag: ${{ steps.version.outputs.version_tag }}"
          if git tag ${{ steps.version.outputs.version_tag }}; then
            git push origin ${{ steps.version.outputs.version_tag }}
            echo "Tag created and pushed successfully"
          else
            echo "Failed to create tag"
            exit 1
          fi